version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/server

permissions:
  - object: /home/ubuntu/server/
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 10
      runas: root